# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e97b817121b1dadea06e877333e94cf85aa6d65a1038e19e19068fe4435b128bbfaa25b6126813cfaf425774e4d825a6acc855746ca9a3b3714f422acabea6e

test:
  secret_key_base: 75550b15730b954b9739a08c38bdb22f67345d3403045096db6319d77e895a15a2560da6b81dd694cf78f2bba5210f925b19f61f00e5452ccf394aac7a364fcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
